package types

import (
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

// x/truthgpt module sentinel errors
var (
	ErrOracleProviderExists           = sdkerrors.Register(ModuleName, 1, "oracle provider already exists")
	ErrOracleProviderNotFound         = sdkerrors.Register(ModuleName, 2, "oracle provider not found")
	ErrInvalidOracleProviderName      = sdkerrors.Register(ModuleName, 3, "invalid oracle provider name")
	ErrInvalidOracleProviderDesc      = sdkerrors.Register(ModuleName, 4, "invalid oracle provider description")
	ErrInvalidOracleProviderWebsite   = sdkerrors.Register(ModuleName, 5, "invalid oracle provider website")
	ErrInvalidOracleProviderIdentity  = sdkerrors.Register(ModuleName, 6, "invalid oracle provider identity")
	ErrInvalidStakedAmount            = sdkerrors.Register(ModuleName, 7, "invalid staked amount")
	ErrInsufficientStakedAmount       = sdkerrors.Register(ModuleName, 8, "insufficient staked amount")
	ErrMaxProvidersReached            = sdkerrors.Register(ModuleName, 9, "maximum number of providers reached")
	ErrOracleRequestNotFound          = sdkerrors.Register(ModuleName, 10, "oracle request not found")
	ErrInvalidOracleScriptID          = sdkerrors.Register(ModuleName, 11, "invalid oracle script ID")
	ErrOracleScriptNotFound           = sdkerrors.Register(ModuleName, 12, "oracle script not found")
	ErrInvalidCalldata                = sdkerrors.Register(ModuleName, 13, "invalid calldata")
	ErrCalldataTooLarge               = sdkerrors.Register(ModuleName, 14, "calldata too large")
	ErrInvalidAskCount                = sdkerrors.Register(ModuleName, 15, "invalid ask count")
	ErrInvalidMinCount                = sdkerrors.Register(ModuleName, 16, "invalid min count")
	ErrInvalidClientID                = sdkerrors.Register(ModuleName, 17, "invalid client ID")
	ErrInvalidFeeLimit                = sdkerrors.Register(ModuleName, 18, "invalid fee limit")
	ErrInsufficientFeeLimit           = sdkerrors.Register(ModuleName, 19, "insufficient fee limit")
	ErrInvalidPrepareGas              = sdkerrors.Register(ModuleName, 20, "invalid prepare gas")
	ErrInvalidExecuteGas              = sdkerrors.Register(ModuleName, 21, "invalid execute gas")
	ErrInvalidTimeoutBlocks           = sdkerrors.Register(ModuleName, 22, "invalid timeout blocks")
	ErrOracleResponseNotFound         = sdkerrors.Register(ModuleName, 23, "oracle response not found")
	ErrInvalidResult                  = sdkerrors.Register(ModuleName, 24, "invalid result")
	ErrResultTooLarge                 = sdkerrors.Register(ModuleName, 25, "result too large")
	ErrInvalidConfidence              = sdkerrors.Register(ModuleName, 26, "invalid confidence")
	ErrRequestNotActive               = sdkerrors.Register(ModuleName, 27, "request not active")
	ErrRequestAlreadyResponded        = sdkerrors.Register(ModuleName, 28, "request already responded to by this provider")
	ErrRequestExpired                 = sdkerrors.Register(ModuleName, 29, "request expired")
	ErrRequestCanceled                = sdkerrors.Register(ModuleName, 30, "request canceled")
	ErrRequestCompleted               = sdkerrors.Register(ModuleName, 31, "request completed")
	ErrUnauthorized                   = sdkerrors.Register(ModuleName, 32, "unauthorized")
	ErrInvalidReputationChange        = sdkerrors.Register(ModuleName, 33, "invalid reputation change")
	ErrInvalidReason                  = sdkerrors.Register(ModuleName, 34, "invalid reason")
	ErrDataSourceNotFound             = sdkerrors.Register(ModuleName, 35, "data source not found")
	ErrInvalidDataSourceName          = sdkerrors.Register(ModuleName, 36, "invalid data source name")
	ErrInvalidDataSourceDesc          = sdkerrors.Register(ModuleName, 37, "invalid data source description")
	ErrInvalidExecutable              = sdkerrors.Register(ModuleName, 38, "invalid executable")
	ErrExecutableTooLarge             = sdkerrors.Register(ModuleName, 39, "executable too large")
	ErrInvalidFee                     = sdkerrors.Register(ModuleName, 40, "invalid fee")
	ErrInvalidOwner                   = sdkerrors.Register(ModuleName, 41, "invalid owner")
	ErrInvalidOracleScriptName        = sdkerrors.Register(ModuleName, 42, "invalid oracle script name")
	ErrInvalidOracleScriptDesc        = sdkerrors.Register(ModuleName, 43, "invalid oracle script description")
	ErrInvalidSchema                  = sdkerrors.Register(ModuleName, 44, "invalid schema")
	ErrInvalidSourceCodeURL           = sdkerrors.Register(ModuleName, 45, "invalid source code URL")
	ErrInvalidCode                    = sdkerrors.Register(ModuleName, 46, "invalid code")
	ErrCodeTooLarge                   = sdkerrors.Register(ModuleName, 47, "code too large")
	ErrTooManyRequests                = sdkerrors.Register(ModuleName, 48, "too many requests in this block")
	ErrTooManyResponses               = sdkerrors.Register(ModuleName, 49, "too many responses in this block")
	ErrProviderReputationTooLow       = sdkerrors.Register(ModuleName, 50, "provider reputation too low")
	ErrInvalidProviderResponseHistory = sdkerrors.Register(ModuleName, 51, "invalid provider response history")
	ErrInvalidProviderRewards         = sdkerrors.Register(ModuleName, 52, "invalid provider rewards")
	ErrInvalidProviderStats           = sdkerrors.Register(ModuleName, 53, "invalid provider stats")
	ErrInvalidResultData              = sdkerrors.Register(ModuleName, 54, "invalid result data")
	ErrTooManyRawRequests             = sdkerrors.Register(ModuleName, 55, "too many raw requests")
	ErrInvalidRawRequest              = sdkerrors.Register(ModuleName, 56, "invalid raw request")
	ErrInvalidReportData              = sdkerrors.Register(ModuleName, 57, "invalid report data")
	ErrInvalidValidator               = sdkerrors.Register(ModuleName, 58, "invalid validator")
	ErrInvalidReporter                = sdkerrors.Register(ModuleName, 59, "invalid reporter")
	ErrInvalidDataRequest             = sdkerrors.Register(ModuleName, 60, "invalid data request")
)