package types

import (
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

// NeuroPOS module sentinel errors
var (
	ErrEmptyValidatorAddr               = sdkerrors.Register(ModuleName, 1, "empty validator address")
	ErrNoValidatorFound                  = sdkerrors.Register(ModuleName, 2, "validator not found")
	ErrValidatorOwnerExists              = sdkerrors.Register(ModuleName, 3, "validator already exists for this operator address")
	ErrValidatorPubKeyExists             = sdkerrors.Register(ModuleName, 4, "validator already exists for this pubkey")
	ErrValidatorPubKeyTypeNotSupported   = sdkerrors.Register(ModuleName, 5, "validator pubkey type is not supported")
	ErrValidatorJailed                   = sdkerrors.Register(ModuleName, 6, "validator is jailed")
	ErrInvalidDelegation                 = sdkerrors.Register(ModuleName, 7, "invalid delegation")
	ErrInvalidInput                      = sdkerrors.Register(ModuleName, 8, "invalid input")
	ErrInvalidDelegator                  = sdkerrors.Register(ModuleName, 9, "invalid delegator")
	ErrInvalidMoniker                    = sdkerrors.Register(ModuleName, 10, "invalid validator moniker")
	ErrInvalidCommissionRate             = sdkerrors.Register(ModuleName, 11, "invalid validator commission rate")
	ErrNoDelegatorForAddress             = sdkerrors.Register(ModuleName, 12, "delegator does not exist for that address")
	ErrBadDelegationAmount               = sdkerrors.Register(ModuleName, 13, "invalid delegation amount")
	ErrNoDelegation                      = sdkerrors.Register(ModuleName, 14, "no delegation for this (delegator, validator) pair")
	ErrNoUnbondingDelegation             = sdkerrors.Register(ModuleName, 15, "no unbonding delegation found")
	ErrNoRedelegation                    = sdkerrors.Register(ModuleName, 16, "no redelegation found")
	ErrSelfDelegationBelowMinimum        = sdkerrors.Register(ModuleName, 17, "validator's self delegation below minimum")
	ErrTooManyValidators                 = sdkerrors.Register(ModuleName, 18, "too many validators")
	ErrInsufficientShares                = sdkerrors.Register(ModuleName, 19, "insufficient delegation shares")
	ErrDelegatorShareExRateInvalid       = sdkerrors.Register(ModuleName, 20, "cannot delegate to validators with invalid (zero) ex-rate")
	ErrBadRemoveValidatorPower           = sdkerrors.Register(ModuleName, 21, "invalid attempt to remove validator power")
	ErrCantUndelegate                    = sdkerrors.Register(ModuleName, 22, "cannot undelegate")
	ErrCantRedelegate                    = sdkerrors.Register(ModuleName, 23, "cannot redelegate")
	ErrBadRedelegationDst                = sdkerrors.Register(ModuleName, 24, "redelegation destination validator not found")
	ErrTransitiveRedelegation            = sdkerrors.Register(ModuleName, 25, "redelegation to this validator already in progress; first redelegation to this validator must complete before next redelegation")
	ErrUnbondingOnHoldNotFound           = sdkerrors.Register(ModuleName, 26, "unbonding delegation on hold not found")
	ErrValidatorNotJailed                = sdkerrors.Register(ModuleName, 27, "validator not jailed")
	ErrValidatorStatus                   = sdkerrors.Register(ModuleName, 28, "validator status is invalid")
	ErrValidatorTombstoned               = sdkerrors.Register(ModuleName, 29, "validator is tombstoned")
	ErrNoHistoricalInfo                  = sdkerrors.Register(ModuleName, 30, "no historical info found")
	ErrNoNeuralNetworkFound              = sdkerrors.Register(ModuleName, 31, "neural network not found")
	ErrInvalidNeuralNetworkArchitecture  = sdkerrors.Register(ModuleName, 32, "invalid neural network architecture")
	ErrInvalidNeuralNetworkWeights       = sdkerrors.Register(ModuleName, 33, "invalid neural network weights")
	ErrInvalidTrainingData               = sdkerrors.Register(ModuleName, 34, "invalid training data")
	ErrInvalidLearningRate               = sdkerrors.Register(ModuleName, 35, "invalid learning rate")
	ErrInvalidEpochs                     = sdkerrors.Register(ModuleName, 36, "invalid epochs")
	ErrInvalidPredictionInput            = sdkerrors.Register(ModuleName, 37, "invalid prediction input")
	ErrInvalidValidatorReputation        = sdkerrors.Register(ModuleName, 38, "invalid validator reputation")
	ErrInvalidPerformanceScore           = sdkerrors.Register(ModuleName, 39, "invalid performance score")
	ErrInvalidReputationChange           = sdkerrors.Register(ModuleName, 40, "invalid reputation change")
	ErrValidatorReputationTooLow         = sdkerrors.Register(ModuleName, 41, "validator reputation below minimum threshold")
	ErrTooManyMissedBlocks               = sdkerrors.Register(ModuleName, 42, "validator has missed too many blocks")
	ErrInvalidSlashFraction              = sdkerrors.Register(ModuleName, 43, "invalid slash fraction")
	ErrInvalidSigningInfo                = sdkerrors.Register(ModuleName, 44, "invalid signing info")
	ErrNeuralNetworkTrainingInProgress   = sdkerrors.Register(ModuleName, 45, "neural network training already in progress")
	ErrNeuralNetworkUpdateInProgress     = sdkerrors.Register(ModuleName, 46, "neural network update already in progress")
	ErrInvalidNeuralNetworkInfluenceRate = sdkerrors.Register(ModuleName, 47, "invalid neural network influence rate")
	ErrInvalidReputationRate             = sdkerrors.Register(ModuleName, 48, "invalid reputation rate")
)